export enum ActionType {
    GET_ALL = "GET_ALL",
    CREATE_POST  = "CREATE_POST",
    UPDATE_POST = "UPDATE_POST",
    DELETE_POST = "DELETE_POST",
    LIKE_POST = "LIKE_POST",
    LIKE_ERROR = "LIKE_ERROR",
    POST_ERROR = "POST_ERROR",

    CREATE_COMMENT = "CREATE_COMMENT",
    GET_COMMENT = "GET_COMMENT",
    DELETE_COMMENT = "DELETE_COMMENT",
    UPDATE_COMMENT = "UPDATE_COMMENT",
    COMMENT_ERROR = "COMMENT_ERROR",

    CREATE_USER = "CREATE_USER",
    LOGIN_USER = "LOGIN_USER",
    LOG_OUT = "LOG_OUT",
    USER_ERROR = "USER_ERROR"
}